spring:
  datasource:
    url: jdbc:mysql://127.0.01:3306/mpt_toolkit_auth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat